@startuml

browser -> listener : SAML login request
listener -> sequence_1 : SAML login request



browser -> http_inbound_travelocity : SAML login request
http_inbound_travelocity -> sequence_1 : request

hnote over sequence_1 : SAML request process
hnote over sequence_1 : OIDC request build
sequence_1 -> http_inbound_travelocity : Redirect to IDP
http_inbound_travelocity -> browser : Redirect to IDP

browser -> OIDC_IdP
OIDC_IdP -> browser : login page
browser -> OIDC_IdP : Submit credentials

OIDC_IdP -> http_inbound_commonauth : ID token
http_inbound_commonauth -> sequence_2 : ID token


hnote over sequence_2 : OIDC response process
hnote over sequence_2 : SAML response build

sequence_2 -> http_inbound_commonauth : SAML response
http_inbound_commonauth -> browser : SAML response
@enduml