@startuml

participant user_agent
participant service_provider
participant "http_inbound:\n/travelocity" as http_inbound_travelocity
participant "sequence:\ntravelocity" as sequence_1
participant oidc_fidp

note over http_inbound_travelocity
[host]:[port]/travelocity
This is a service provider specific endpoint
for inbound request and callbacks
end note

user_agent -> http_inbound_travelocity : Inbound request
http_inbound_travelocity -> sequence_1 : Inbound request

note over sequence_1
A filter checks <b>Referer</b> header
to identify the SP's request.
<font color=red>Should change to a payload
<font color=red>based filter
end note

alt condition(source("Referer", Scope.Transport), pattern(".*samlsso.*"))

hnote over sequence_1 : SAML request process
hnote over sequence_1 : OIDC request build

sequence_1 -> http_inbound_travelocity : Redirects to IDP
http_inbound_travelocity -> user_agent : Redirects to IDP

else redirect form IDP with ID token

hnote over sequence_1 : OIDC response process
hnote over sequence_1 : SAML response build

sequence_1 -> http_inbound_travelocity : SAML response\nin HTML form
http_inbound_travelocity -> user_agent : SAML response in HTML from

end

@enduml