@startuml
participant browser as user_agent
participant service_provider
participant "http_inbound:\n/travelocity" as http_inbound_travelocity
participant "sequence:\ntravelocity" as sequence_1
participant "http_inbound:\n/commonauth" as http_inbound_commonauth
participant "sequence:\ncommonauth" as sequence_2
participant oidc_fidp

note over http_inbound_travelocity
[host]:[port]/travelocity
This is a service provider specific endpoint
for inbound requests
end note

note over http_inbound_commonauth
[host]:[port]/commonauth
This is a common callback endpoint
for all SPs
end note

user_agent -> service_provider : Access resource
service_provider -> user_agent : Redirects to bus\nwith SAML login request
user_agent -> http_inbound_travelocity : Follows redirect with SAML login request
http_inbound_travelocity -> sequence_1 : SAML login request

hnote over sequence_1 : SAML request process
hnote over sequence_1 : OIDC request build

sequence_1 -> http_inbound_travelocity : Redirects to IDP
http_inbound_travelocity -> user_agent : Redirects to IDP
user_agent -> oidc_fidp : Follows redirect: GET /authorize [Implicit]

oidc_fidp -> user_agent : Redirects to /commonauth with ID token
user_agent -> http_inbound_commonauth : Follows redirect with ID token
http_inbound_commonauth -> sequence_2 : ID token

hnote over sequence_2 : OIDC response process
hnote over sequence_2 : SAML response build

sequence_2 -> http_inbound_commonauth : SAML response\nin HTML form
http_inbound_commonauth -> user_agent : SAML response in HTML from
user_agent -> service_provider : POST SAML response
service_provider -> user_agent : Supply resource

@enduml