@startuml
Title : Inbound SAML with Local IDP


participant "SP : ODEL" as SP
participant "IDP : LOCAL" as IDP
database "US : LDAP" as US_ODEL


autonumber

hnote left SP
SAML
end hnote
 -> SP
activate SP
SP -> SP : Validate Request
SP -> IDP : \tAuthenticate
    activate IDP #lightBlue
    IDP -> IDP : Claim Mapping
    IDP -> SP : Authentication Response
    deactivate IDP
SP -> SP : Build Response
hnote left SP
SAML
end hnote
 <- SP
deactivate SP


@enduml